name: Check and Build Docker Image

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "0 0 * * 0"  # Runs once a week (every Sunday at midnight)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Get latest release tag from Aldaviva/GandiDynamicDns
      id: get_release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/Aldaviva/GandiDynamicDns/releases/latest | jq -r .tag_name)
        echo "tag=$latest_release" >> $GITHUB_ENV

    - name: Check if the release is new
      run: |
        if [ "${{ secrets.LAST_RELEASE }}" != "${{ env.tag }}" ]; then
          echo "New release found: ${{ env.tag }}"
          echo "LAST_RELEASE=${{ env.tag }}" >> $GITHUB_ENV
        else
          echo "No new release found"
          exit 0
        fi  

    - name: Build and push Docker image
      if: env.LAST_RELEASE == env.tag
      run: |
        docker build -t d0mmi/gandidynamicdns:${{ env.tag }} .
        docker tag d0mmi/gandidynamicdns:${{ env.tag }} d0mmi/gandidynamicdns:latest
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push d0mmi/gandidynamicdns:${{ env.tag }}
        docker push d0mmi/gandidynamicdns:latest